import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PrintScreen extends StatelessWidget {
  final Uint8List qrImageBytes;
  final String qrData;

  const PrintScreen({
    super.key,
    required this.qrImageBytes,
    required this.qrData,
  });

  /// Versi Lite: Hanya berisi elemen esensial untuk mempercepat rendering
  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();
    final qrImage = pw.MemoryImage(qrImageBytes);

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                // Header Sederhana
                pw.Text('QR CODE REPORT', 
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 30),
                
                // Gambar QR (Ukuran statis agar layouting cepat)
                pw.Image(qrImage, width: 220, height: 220),
                
                pw.SizedBox(height: 30),
                
                // Data QR tanpa styling kompleks
                pw.Text('Data: $qrData', 
                  textAlign: pw.TextAlign.center,
                  style: const pw.TextStyle(fontSize: 14)),
                
                pw.SizedBox(height: 50),
                
                // Footer satu baris
                pw.Text('Generated by QR S&G App', 
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              ],
            ),
          );
        },
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Cetak QR'),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: PdfPreview(
        // Optimasi: Gunakan format A4 tetap untuk mengurangi kalkulasi layout ulang
        initialPageFormat: PdfPageFormat.a4,
        build: (format) => _generatePdf(format),
        
        // Matikan fitur-fitur yang tidak perlu untuk meringankan UI
        allowSharing: true,
        allowPrinting: true,
        canChangePageFormat: false, // Mematikan opsi ganti ukuran kertas (A4, Letter, dll)
        canDebug: false, // Pastikan debug mode mati
        
        // Tampilan loading sederhana
        loadingWidget: const Center(child: CircularProgressIndicator(strokeWidth: 2)),
      ),
    );
  }
}