import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';
import 'package:qr_generator_and_scanner/main.dart'; 
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

// Konfigurasi Warna Tema
const Color primaryColor = Color(0xFF3A2EC3);

const List<Color> qrColors = [
  Colors.white,
  Color(0xFFF5F5F5),
  Color(0xFFFFE0B2),
  Color(0xFFFFF9C4),
  Color(0xFFC8E6C9),
  Color(0xFFB2EBF2),
  Color(0xFFE1BEE7),
  Color(0xFFFFCDD2),
  Color(0xFFD1C4E9),
  Color(0xFFBBDEFB),
];

class QrGeneratorScreen extends StatefulWidget {
  const QrGeneratorScreen({super.key});

  @override
  State<QrGeneratorScreen> createState() => _QrGeneratorScreenState();
}

class _QrGeneratorScreenState extends State<QrGeneratorScreen> {
  final ScreenshotController _screenshotController = ScreenshotController();
  String? _qrData;
  Color _qrColor = Colors.white;

  // --- LOGIKA HELPER ---

  void _showLoading(String message) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        content: Row(
          children: [
            const CircularProgressIndicator(color: primaryColor),
            const SizedBox(width: 20),
            Text(message, style: const TextStyle(fontWeight: FontWeight.w500)),
          ],
        ),
      ),
    );
  }

  void _showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.redAccent : Colors.green,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  // --- LOGIKA UTAMA (SHARE & PDF) ---

  Future<void> _handleShare({required bool isEmailFriendly}) async {
    if (_qrData == null) return;

    _showLoading("Menyiapkan file...");
    try {
      final Uint8List? imageBytes = await _screenshotController.capture(pixelRatio: 2.0);
      Navigator.pop(context); // Tutup loading

      if (imageBytes != null) {
        final String fileName = 'QR_${DateTime.now().millisecondsSinceEpoch}.png';
        await Share.shareXFiles(
          [XFile.fromData(imageBytes, name: fileName, mimeType: 'image/png')],
          subject: isEmailFriendly ? 'QR Code dari QR S&G App' : null,
          text: 'Ini QR Code untuk: $_qrData',
        );
      }
    } catch (e) {
      Navigator.pop(context);
      _showSnackBar("Gagal membagikan: $e", isError: true);
    }
  }

  Future<void> _generateAndSavePdf() async {
    if (_qrData == null) return;

    _showLoading("Memproses PDF...");
    try {
      final Uint8List? qrBytes = await _screenshotController.capture();
      if (qrBytes == null) throw Exception("Gagal mengambil gambar QR");

      final pdf = pw.Document();
      final qrImage = pw.MemoryImage(qrBytes);

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Stack(
              children: [
                // Watermark
                pw.Center(
                  child: pw.Opacity(
                    opacity: 0.05,
                    child: pw.Text('QR S&G APP', 
                      style: pw.TextStyle(fontSize: 80, fontWeight: pw.FontWeight.bold)),
                  ),
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.center,
                  children: [
                    pw.Text('OFFICIAL QR REPORT', 
                      style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo)),
                    pw.Divider(thickness: 1),
                    pw.SizedBox(height: 50),
                    pw.Center(child: pw.Image(qrImage, width: 250, height: 250)),
                    pw.SizedBox(height: 30),
                    pw.Text('Encoded Data:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.Text(_qrData!, textAlign: pw.TextAlign.center),
                    pw.Spacer(),
                    pw.Text('Generated by QR S&G App - Wibowo Assariy', 
                      style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                  ],
                ),
              ],
            );
          },
        ),
      );

      // Simpan ke Downloads
      final directory = await getExternalStorageDirectory(); 
      final String path = "${directory!.path}/QR_Report_${DateTime.now().millisecondsSinceEpoch}.pdf";
      final file = File(path);
      await file.writeAsBytes(await pdf.save());

      Navigator.pop(context); // Tutup loading
      
      // Buka Otomatis
      await OpenFile.open(path);
      _showSnackBar("PDF disimpan & dibuka");
    } catch (e) {
      if (Navigator.canPop(context)) Navigator.pop(context);
      _showSnackBar("Error PDF: $e", isError: true);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Variabel pengecekan tombol
    bool isButtonActive = _qrData != null && _qrData!.isNotEmpty;

    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FD),
      appBar: AppBar(
        title: const Text('Create QR', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        backgroundColor: primaryColor,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: Colors.white, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Stack(
        children: [
          Container(
            height: MediaQuery.of(context).size.height * 0.15,
            decoration: const BoxDecoration(
              color: primaryColor,
              borderRadius: BorderRadius.only(bottomLeft: Radius.circular(40), bottomRight: Radius.circular(40)),
            ),
          ),
          SafeArea(
            child: SingleChildScrollView(
              physics: const BouncingScrollPhysics(),
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 10),
              child: Column(
                children: [
                  Container(
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(32),
                      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 25, offset: const Offset(0, 15))],
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // QR PREVIEW
                        Center(
                          child: Screenshot(
                            controller: _screenshotController,
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 300),
                              padding: const EdgeInsets.all(20),
                              decoration: BoxDecoration(
                                color: _qrColor,
                                borderRadius: BorderRadius.circular(24),
                                border: Border.all(color: Colors.grey.shade100, width: 2),
                              ),
                              child: _qrData == null
                                  ? Column(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Icon(Icons.qr_code_2_rounded, size: 160, color: Colors.grey.shade200),
                                        const Text('Preview QR', style: TextStyle(color: Colors.grey)),
                                      ],
                                    )
                                  : SizedBox(
                                      height: 180,
                                      width: 180,
                                      child: PrettyQrView.data(
                                        data: _qrData!,
                                        decoration: const PrettyQrDecoration(shape: PrettyQrSmoothSymbol()),
                                      ),
                                    ),
                            ),
                          ),
                        ),
                        const SizedBox(height: 32),
                        
                        // INPUT
                        const Text('Konten QR', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
                        const SizedBox(height: 8),
                        TextField(
                          decoration: InputDecoration(
                            hintText: 'Masukkan link atau teks...',
                            prefixIcon: const Icon(Icons.link_rounded, color: primaryColor),
                            border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
                            filled: true,
                            fillColor: const Color(0xFFF3F5F9),
                          ),
                          onChanged: (value) {
                            setState(() {
                              _qrData = value.trim().isEmpty ? null : value.trim();
                              globalQrData = _qrData;
                            });
                          },
                        ),
                        
                        const SizedBox(height: 32),
                        const Text('Warna Latar Belakang', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
                        const SizedBox(height: 16),
                        
                        // COLOR PICKER
                        SizedBox(
                          height: 55,
                          child: ListView.separated(
                            scrollDirection: Axis.horizontal,
                            itemCount: qrColors.length,
                            separatorBuilder: (_, __) => const SizedBox(width: 12),
                            itemBuilder: (context, index) {
                              bool isSelected = _qrColor == qrColors[index];
                              return GestureDetector(
                                onTap: () => setState(() => _qrColor = qrColors[index]),
                                child: AnimatedContainer(
                                  duration: const Duration(milliseconds: 200),
                                  width: 48, height: 48,
                                  decoration: BoxDecoration(
                                    color: qrColors[index],
                                    shape: BoxShape.circle,
                                    border: Border.all(color: isSelected ? primaryColor : Colors.black12, width: isSelected ? 3 : 1),
                                  ),
                                  child: isSelected ? const Icon(Icons.check, size: 22, color: primaryColor) : null,
                                ),
                              );
                            },
                          ),
                        ),
                        
                        const SizedBox(height: 32),
                        const Divider(height: 1),
                        const SizedBox(height: 24),
                        
                        // ACTION BUTTONS
                        Row(
                          children: [
                            _buildActionButton(
                              label: 'Reset',
                              icon: Icons.refresh_rounded,
                              color: Colors.grey.shade100,
                              textColor: Colors.black87,
                              onTap: () => setState(() { _qrData = null; _qrColor = Colors.white; }),
                            ),
                            const SizedBox(width: 12),
                            _buildActionButton(
                              label: 'Share QR',
                              icon: Icons.ios_share_rounded,
                              color: isButtonActive ? primaryColor : Colors.grey.shade300,
                              textColor: isButtonActive ? Colors.white : Colors.grey,
                              onTap: isButtonActive ? () => _handleShare(isEmailFriendly: false) : () {},
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        
                        // PDF BUTTON (Finishing Requirement)
                        _buildActionButton(
                          label: 'Simpan & Cetak PDF',
                          icon: Icons.picture_as_pdf_rounded,
                          color: isButtonActive ? const Color(0xFFE8F5E9) : Colors.grey.shade200,
                          textColor: isButtonActive ? Colors.green.shade700 : Colors.grey,
                          isFullWidth: true,
                          onTap: isButtonActive ? _generateAndSavePdf : () {},
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildActionButton({required String label, required IconData icon, required Color color, required Color textColor, required VoidCallback onTap, bool isFullWidth = false}) {
    Widget button = InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(16),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 16),
        decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(16)),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, size: 20, color: textColor),
            const SizedBox(width: 10),
            Text(label, style: TextStyle(color: textColor, fontWeight: FontWeight.bold, fontSize: 14)),
          ],
        ),
      ),
    );
    return isFullWidth ? button : Expanded(child: button);
  }
}